# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilmeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7.0'
  pod 'AlamofireImage', '~> 3.4.0'
  # Pods for teste
  
  target 'FilmeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FilmeAppUITests' do
    # Pods for testing
  end

end
